### ISSUE TITLE
USER STORY: Suggest characters

### ISSUE THREAD

**Issue by jensbrauer** [jensbrauer/rateYourSwordfighter#10]
As a **user** I can **suggest swordfighters that should be added to the ranking list** so that **my favourite characters are featured on the page**

**Comment by jensbrauer** [comment]
**REQUIREMENTS**

- [ ] Users should be able to submit a form with input fields to create a swordfighter in the swordfighter model
- [ ] Administrators should be able to crud the suggestion and "approve for publishing on site"
- [ ] Users should be able to see a list of the characters they suggested and their status

**Comment by jensbrauer** [comment]
**TASKS**

- [ ] Update swordfighter model with statusfield "Panding apporval, published, published with edits or disapproved"
- [ ] Create a "Contribute" tab and html template
- [ ] create a get and post view for the form
