### ISSUE TITLE
USER STORY: Edit and delete suggestions

### ISSUE THREAD

**Issue by jensbrauer** [jensbrauer/rateYourSwordfighter#16]
As a **user** I can **edit and delete my suggestions before approval** so that **my suggestions are actually what I want them to be**

**Comment by jensbrauer** [comment]
**REQUIREMENTS**

- [ ] Users should have a delete button option in their suggested swordfighters card that give them the ability to delete their suggestions before they are published
- [ ] User should be prompted with an R U sure message before final delete to avoid accidents

**Comment by jensbrauer** [comment]
**TASKS**

- [ ] Create delete button in contribute card template
- [ ] Create view and URL to acces the delete form submition page
- [ ] create an "Are you sure?" template
- [ ] create post view to delete a swordfighter object
- [ ] Create submit delete form in "Are you sure" template
