### ISSUE TITLE
USER STORY: View Swordfighters

### ISSUE THREAD

**Issue by jensbrauer** [jensbrauer/rateYourSwordfighter#2]
As a **visitor** I can **click on swordfighters in the ranking list** so that **I can acces more information on their individual page**

**Comment by jensbrauer** [comment]
**Acceptance criteria**

- [ ] I can click on a swordfighter card in the rankingslist view and be forwarded to their individual page
- [ ] The pages should be generated based on the swordfighter model and not hard coded

**Comment by jensbrauer** [comment]
**TASKS**

- [ ] Create a swordfighter view 
- [ ] Create a swordfighter.html template
- [ ] Add some extra information from the swordfighter model
- [ ] Add a navigation feature to return to listview
- [ ] Create som initial bootstrap styling
