### ISSUE TITLE
USER STORY: Sign up

### ISSUE THREAD

**Issue by jensbrauer** [jensbrauer/rateYourSwordfighter#4]
As a **visitor** I can **sign up for a users account** so that **I can become a user with extended functionality**

**Comment by jensbrauer** [comment]
**Requirements**

- [ ] Visitors should be able to find a link to a signup page from all views
- [ ] Visitors should be able to register with and email, choose a username and a password through a signup page
- [ ] visitors should get a respons message telling them that the account has been registered and be presented with the option to sign in

**Comment by jensbrauer** [comment]
**TASKS**

- [ ] Set up allauth authentication
- [ ] Activate navbar functionality to base.html with link to signup
- [ ] Create and style a signup page
