### ISSUE TITLE
USER STORY: Place ratings

### ISSUE THREAD

**Issue by jensbrauer** [jensbrauer/rateYourSwordfighter#6]
As a **user** I can **place ratings on swordfighters** so that **I can impact the swordfighters ranking list**

**Comment by jensbrauer** [comment]
**Requirements**

- [ ] Users can push "upvote button" on character card on rankingslist and/or on character page
- [ ] One upvote per user
- [ ] Users should be able to remove their upvote

**Comment by jensbrauer** [comment]
**TASKS**

- [ ] Update swordfighter datamodel with upvotes field
- [ ] Add buttons to character page view and swordfighter card
- [ ] Add functionality to the buttons to update swordfighter model
