### ISSUE TITLE
USER STORY: Place comments

### ISSUE THREAD

**Issue by jensbrauer** [jensbrauer/rateYourSwordfighter#7]
As a **user** I can **submit comments on swordfighters** so that **I can give a qualitative description of my opinion to influence others**

**Comment by jensbrauer** [comment]
**REQUIREMENTS**

- [ ] Users should be able to place comments in a "conversation" on the individual character pages
- [ ] Users should be able to Create, Read and Delete their own comments
- [ ] Users should be able to "report" unappropriate comments from other users
- [ ] Comments should be sorted by -newest first
- [ ] Comments should reveal: Who posted? What their comment was and when they posted.

**Comment by jensbrauer** [comment]
**TASKS**

- [ ] Add a new comments model to the models
- [ ] Create a new view for the comments
- [ ] Extend the character page template with new comments section with Create, read, report and delete features
