### ISSUE TITLE
USER STORY: Report issues

### ISSUE THREAD

**Issue by jensbrauer** [jensbrauer/rateYourSwordfighter#8]
As a **users** I can **flag bad comments and content** so that **I can help maintain healthy discussions and a relevant forum**

**Comment by jensbrauer** [comment]
**Tasks**

- [ ] Create a flag attribute to the comments model so many users can "flag" many comments and toggle their flag
- [ ] Add toggle button on the comments so that a user has the "flag" option on other users comments
- [ ] add a flag comment view
- [ ] add message to the post function
